### ISSUE TITLE
normalize_input function handles ';' characters badly

### ISSUE THREAD

**Issue by p3t9a** [Pocsek/mini-dbms#11]
';' - characters usually remain concatenated to one of the tokens after sqlparse.format() call
ex.:
input:
  CREATE DATABASE Lab1_Fitness;
  USE Lab1_Fitness;
output:
  create database Lab1_Fitness ;use Lab1_Fitness ;

input:
  one; two; three;
output:
  one ;two ;three ;

**Comment by csongorszasz** [comment]
Fixed
