### ISSUE TITLE
Tab completion: sometimes when it should be suggesting table names, it only shows database names

### ISSUE THREAD

**Issue by csongorszasz** [Pocsek/mini-dbms#45]
Example:

![image](https://github.com/Pocsek/mini-dbms/assets/75858356/5020d924-fa13-4fc8-bc3c-b23176ac96d1)

**Comment by p3t9a** [comment]
it's not a bug it's  feature. fixed it for u

**Comment by csongorszasz** [comment]
You are indeed funny, colleague
